# Generated by Django 5.0.dev20230825192722 on 2023-09-01 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='patientName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hibahs.patientdata'),
        ),
    ]
