# Generated by Django 5.0.dev20230825192722 on 2023-09-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0003_alter_uploadedfile_patientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='patientNIK',
            field=models.CharField(default=1, max_length=225, verbose_name='NIK Pasien'),
            preserve_default=False,
        ),
    ]
