# Generated by Django 5.0.dev20230825192722 on 2023-09-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0004_patientdata_patientnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='patientSex',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin'),
        ),
    ]
