# Generated by Django 5.0.dev20230825192722 on 2023-09-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0005_alter_patientdata_patientsex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='patientDateBorn',
            new_name='patientBirthDate',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='patientNIK',
            new_name='patientNationalID',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='patientSex',
        ),
        migrations.AddField(
            model_name='patientdata',
            name='patientGender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1, verbose_name='Jenis Kelamin'),
        ),
    ]
