# Generated by Django 5.0.dev20230825192722 on 2023-09-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0006_rename_patientdateborn_patientdata_patientbirthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='diagnosisResult',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='imageDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Image diambil (mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='limeImageResult',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
