# Generated by Django 5.0.dev20230825192722 on 2023-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0007_uploadedfile_diagnosisresult_uploadedfile_imagedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='imageDate',
            field=models.DateTimeField(verbose_name='Tanggal Image diambil (mm/dd/yyyy)'),
        ),
    ]
