# Generated by Django 4.2.6 on 2023-11-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0008_alter_uploadedfile_imagedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='diagnosisResult',
            field=models.TextField(default=None),
        ),
    ]
