# Generated by Django 4.2.6 on 2023-11-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0009_alter_uploadedfile_diagnosisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='imageDate',
            field=models.DateField(verbose_name='Tanggal Image diambil (mm/dd/yyyy)'),
        ),
    ]
