# Generated by Django 4.2.6 on 2023-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0010_alter_uploadedfile_imagedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='patientBirthDate',
            field=models.DateField(verbose_name='Tanggal Lahir (mm/dd/yyyy)'),
        ),
    ]
