# Generated by Django 4.2.6 on 2023-11-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0011_alter_patientdata_patientbirthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='diagnosisResult',
            field=models.TextField(null=True),
        ),
    ]
