# Generated by Django 4.2.6 on 2023-11-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0016_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='patientNationalID',
            field=models.CharField(max_length=16, verbose_name='NIK Pasien'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
