# Generated by Django 4.2.6 on 2023-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0017_alter_patientdata_patientnationalid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='patientNationalID',
        ),
        migrations.AddField(
            model_name='patientdata',
            name='patientID',
            field=models.CharField(default=None, max_length=16, unique=True, verbose_name='No Pasien'),
        ),
    ]
