# Generated by Django 4.2.6 on 2023-11-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0018_remove_patientdata_patientnationalid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdata',
            options={'verbose_name_plural': 'Data Pasien'},
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patientBirthDate',
            field=models.DateField(verbose_name='Tanggal Lahir'),
        ),
    ]
