# Generated by Django 4.2.6 on 2024-11-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0019_alter_patientdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='file',
            new_name='annotation',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='image',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
