# Generated by Django 4.2.6 on 2024-11-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0020_rename_file_uploadedfile_annotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/')),
                ('predictionResult', models.TextField(blank=True, null=True)),
                ('predictionDate', models.DateField(verbose_name='Tanggal Image diprediksi (mm/dd/yyyy)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='diagnosisResult',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='limeImageResult',
        ),
        migrations.AddField(
            model_name='croppedimage',
            name='rawImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hibahs.uploadedfile'),
        ),
    ]
